//
//  HomeViewController.swift
//  Entertainya
//
//  Created by Karim Cordilia on 31/01/2021.
//  Copyright (c) 2021 Karim Cordilia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol HomeViewControllerProtocol: UIViewControllerRouting {
    func set(interactor: HomeInteractorProtocol)
    func set(router: HomeRouterProtocol)
    func displayMovies(movies: Movies)
}

class HomeViewController: UIViewController, HomeViewControllerProtocol {
    // MARK: Outlets
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: Properties
    private var dataSource = HomeDataSource()
    
    // MARK: DI
    var interactor: HomeInteractorProtocol?
    var router: HomeRouterProtocol?

    func set(interactor: HomeInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: HomeRouterProtocol) {
        self.router = router
    }

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.handleViewDidLoad()
        setupTableView()
    }

    // MARK: Actions
    
    // MARK: Methods
    func displayMovies(movies: Movies) {
        dataSource.set(items: movies.results)
        tableView.reloadData()
    }
    
    func setupTableView() {
//        tableView.delegate = self
        tableView.dataSource = dataSource
        tableView.register(R.nib.movieTableViewCell)
//        tableView.tableFooterView = UIView()
    }
}


