////
//  HomeRouter.swift
//  Entertainya
//
//  Created by Karim Cordilia on 31/01/2021.
//  Copyright (c) 2021 Karim Cordilia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol HomeRouterProtocol {
  func set(viewController: HomeViewControllerProtocol?)
  func route(to scene: HomeRouter.Scene)
}

class HomeRouter: NSObject, HomeRouterProtocol {

    //MARK: DI
    weak var viewController: HomeViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let movieStoryboard: Storyboard

    func set(viewController: HomeViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        movieStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.movieStoryboard = movieStoryboard
    }
}

// MARK: Routing logic
extension HomeRouter {

    enum Scene {
        case movie(_ movie: Int)
    }

    func route(to scene: HomeRouter.Scene) {
        switch scene {
        case .movie(let id):
            guard let vc = movieStoryboard.viewController(identifier: MovieStoryboardId.movie) as? MovieViewController else { return }
            vc.interactor?.getMovie(movieId: id)
            viewController?.show(vc, sender: nil)
        }
    }
}

