//
//  HomeInteractor.swift
//  Entertainya
//
//  Created by Karim Cordilia on 31/01/2021.
//  Copyright (c) 2021 Karim Cordilia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import Moya
import RxSwift

protocol HomeInteractorProtocol {
    func handleViewDidLoad()
}

class HomeInteractor: HomeInteractorProtocol {
    
    // MARK: DI
    var presenter: HomePresenterProtocol
    var provider: MoyaProvider<MovieService>!
    var disposeBag = DisposeBag()
    
    init(presenter: HomePresenterProtocol,
         provider: MoyaProvider<MovieService>) {
        self.presenter = presenter
        self.provider = provider
    }
    
    func handleViewDidLoad() {
        getPopularMovies()
    }

    
    func getPopularMovies() {
        provider.rx
            .request(.getPopularMovies)
            .filterSuccessfulStatusAndRedirectCodes()
            .map(Movies.self)
            .subscribe { [weak self] movies in
                self?.presenter.presentMovies(movies: movies)
            } onError: { error in
                print(error)
            }.disposed(by: disposeBag)

    }
}
