////
//  HomeRouter.swift
//  Entertainya
//
//  Created by Karim Cordilia on 31/01/2021.
//  Copyright (c) 2021 Karim Cordilia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol HomeRouterProtocol {
  func set(viewController: HomeViewControllerProtocol?)
  func route(to scene: HomeRouter.Scene)
}

class HomeRouter: NSObject, HomeRouterProtocol {

    //MARK: DI
    weak var viewController: HomeViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol

    func set(viewController: HomeViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol
    ) {
        self.rootNavigator = rootNavigator
    }
}

// MARK: Routing logic
extension HomeRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: HomeRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

