//
//  MoviePresenter.swift
//  Entertainya
//
//  Created by Karim Cordilia on 02/02/2021.
//  Copyright (c) 2021 Karim Cordilia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol MoviePresenterProtocol {
    func set(viewController: MovieViewControllerProtocol?)
    func presentMovie(movie: Movie)

}

class MoviePresenter: MoviePresenterProtocol {

    // MARK: DI
    weak var viewController: MovieViewControllerProtocol?

    func set(viewController: MovieViewControllerProtocol?) {
        self.viewController = viewController
    }
    // MARK: Methods
    func presentMovie(movie: Movie) {
        viewController?.displayMovie(movie: movie)
    }
}

