//
//  MovieInteractor.swift
//  Entertainya
//
//  Created by Karim Cordilia on 02/02/2021.
//  Copyright (c) 2021 Karim Cordilia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import Moya
import RxSwift

protocol MovieInteractorProtocol {
    func set(movie: Movie)
    func handleViewDidLoad()
}

class MovieInteractor: MovieInteractorProtocol {

    // MARK: Properties
    
    // MARK: DI
    var presenter: MoviePresenterProtocol
    private var movie: Movie?

    init(presenter: MoviePresenterProtocol) {
        self.presenter = presenter
    }
    
    func set(movie: Movie) {
        self.movie = movie
    }
    
    func handleViewDidLoad() {
        guard let movie = self.movie else { return }
        presenter.presentMovie(movie: movie)
    }
}
