//
//  MovieViewController.swift
//  Entertainya
//
//  Created by Karim Cordilia on 02/02/2021.
//  Copyright (c) 2021 Karim Cordilia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import Kingfisher

protocol MovieViewControllerProtocol: UIViewControllerRouting {
    func set(interactor: MovieInteractorProtocol)
    func set(router: MovieRouterProtocol)
    func set(movie: Movie)
    
    func displayMovie(movie: Movie)
}

class MovieViewController: UIViewController, MovieViewControllerProtocol {
    // MARK: Outlets
    @IBOutlet weak var movieImage: UIImageView!
    @IBOutlet weak var movieTitle: UILabel!
    @IBOutlet weak var genreLabel: UILabel!
    @IBOutlet weak var releaseDateLabel: UILabel!
    @IBOutlet weak var runtimeLabel: UILabel!
    @IBOutlet weak var movieDescription: UILabel!
    
    
    // MARK: Properties
    
    // MARK: DI
    var interactor: MovieInteractorProtocol?
    var router: MovieRouterProtocol?

    func set(interactor: MovieInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: MovieRouterProtocol) {
        self.router = router
    }
    
    func set(movie: Movie) {
        interactor?.set(movie: movie)
    }

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.handleViewDidLoad()
    }

    // MARK: Actions

    // MARK: Methods
    
    func displayMovie(movie: Movie) {
        movieTitle.text = movie.title
        movieImage.kf.setImage(with: movie.backdropURL)
        genreLabel.text = movie.genresText
        releaseDateLabel.text = movie.releaseDate
        runtimeLabel.text = "\(movie.runtime ?? 0) Mins"
        movieDescription.text = movie.overview
    }
}


