////
//  MovieRouter.swift
//  Entertainya
//
//  Created by Karim Cordilia on 02/02/2021.
//  Copyright (c) 2021 Karim Cordilia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol MovieRouterProtocol {
  func set(viewController: MovieViewControllerProtocol?)
  func route(to scene: MovieRouter.Scene)
}

class MovieRouter: NSObject, MovieRouterProtocol {

    //MARK: DI
    weak var viewController: MovieViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol

    func set(viewController: MovieViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol
    ) {
        self.rootNavigator = rootNavigator

    }
}

// MARK: Routing logic
extension MovieRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: MovieRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

